---
# .github/workflows/lint.yml
name: Lint

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format clang-tidy cmake shellcheck
          pip3 install cmakelang yamllint
          npm install -g markdownlint-cli2 prettier

      - name: Run lint.sh
        run: bash lint.sh
